services:
  app:
    build:
      context: ./docker/app
    volumes:
      - ./backend:/var/www/app
      # php.iniの記述を、uploads.iniに反映する
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      APP_ENV: local
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./docker/frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: video_streaming
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d video_streaming"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/app
    depends_on:
      - app
      - frontend

volumes:
  db_data:
  frontend_node_modules:
